//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateApp.Api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biens
    {
        public int Id { get; set; }
        public string Reference { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int IdPro { get; set; }
    
        public virtual Proprietaire Proprietaire { get; set; }
    }
}
